pretrain: True
device: 'cuda:0'

data:
  paths:
    df: 'data/secondary_data.csv'
    secondary_struct_df: 'data/secondary_struct.csv'
    bpp_files: 'data/Ribonanza_bpp_files/extra_data/'
  seq_length: 512  # pad to this length
  val_prop: 0.1
  batch_size: 64
  experiment: '2A3_MaP'

model:
  name: 'encoder'
  weights: ''  # path to pretrained network (or none)
  save: None # path to network saving location (or none)
  embedding_cfg:
    num_embeddings: 5  # dict size - should be 4 + padding token when using just RNA inputs
    embedding_dim: 64
  encoder:
    num_layers: 8
    num_frozen_layers: 4 
    layer_cfg:
      d_model: 64  # number of features - embedding dimension!
      nhead: 8  # tunable
      dim_feedforward: 1024  # tunable
      dropout: 0.1  # tunable
      activation: 'gelu'
      layer_norm_eps: 0.00001  # default
      batch_first: True
      norm_first: True  
      bias: True

training:
  epochs: 30
  lr: 1e-4
