pretrain: True
device: 'cuda:0'

data:
  paths:
    df: 'data/train.csv'
    secondary_struct_df: 'data/secondary_struct.csv'
  seq_length: None  # pad to this length
  val_prop: 0.1
  batch_size: 64

model:
  name: 'encoder'
  weights: ''  # path to pretrained network (or none)
  embedding_cfg:
    num_embeddings: 5  # dict size - should be 4 + padding token when using just RNA inputs
    embedding_dim: 64
  encoder:
    num_layers: 6
    layer_cfg:
      d_model: None  # number of features - embedding dimension!
      nhead: 8  # tunable
      dim_feedforward: 1024  # tunable
      dropout: 0.1  # tunable
      activation: 'gelu'
      layer_norm_eps: 1e-5  # default
      batch_first: True
      norm_first: True  
      bias: True

optuna:
  num_trials: 50
  sampler: 'tpe'
  pruner: 'hyperband'
  model: 'encoder'
  params:
    - name: 'nhead'
      type: 'int'
      range_min: 1
      range_max: 10
    - name: 'dim_feedforward'
      type: 'float'
      range_min: 512
      range_max: 1024
    - name: 'dropout'
      type: 'float'
      range_min: 0.1
      range_max: 0.3
    - name: 'some_other_param'
      type: 'bool'